<?php
/**
 * Plugin Name: Team Switch - Theme Updater Host
 * Plugin URI: https://github.com/Team-Switch-Reclamebureau/switch-theme-updater-host
 * Description: Central update proxy that authenticates client sites and relays GitHub releases without sharing the GitHub token. Manage all client sites from one place and remotely revoke access.
 * Version: 0.0.24
 * Author: Team Switch
 * Author URI: https://teamswitch.nl
 * GitHub Repo: Team-Switch-Reclamebureau/switch-theme-updater-host
 * GitHub Branch: main
 * GitHub Path: /
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'STUH_OPTION_CLIENTS',    'stuh_clients' );
define( 'STUH_OPTION_SETTINGS',   'stuh_settings' );
define( 'STUH_OPTION_UNVERIFIED', 'stuh_unverified' );
define( 'STUH_OPTION_WHITELIST',  'stuh_whitelist' );
define( 'STUH_REST_NS',           'stu-host/v1' );

// ============================================================
// Main plugin class
// ============================================================
class STUH_Plugin {

	/** Filename of the mu-plugin we manage. */
	const MU_PLUGIN_FILE = 'stuh-maintenance-bypass.php';

	public function __construct() {
		add_action( 'admin_menu',    [ $this, 'register_admin_menu' ] );
		add_action( 'admin_init',    [ $this, 'handle_admin_actions' ] );
		add_action( 'rest_api_init', [ $this, 'register_rest_routes' ] );
		add_action( 'admin_notices', [ $this, 'maybe_notice_no_token' ] );
		add_action( 'plugins_loaded', [ $this, 'ensure_mu_plugin' ] );

		// Intercept our own plugin update before WordPress tries to HTTP-download
		// from our REST API — which would hit maintenance mode on this same server.
		add_filter( 'upgrader_pre_download', [ $this, 'intercept_self_upgrade' ], 5, 4 );

		// Self-update: check GitHub for new releases and inject into WP update system.
		add_filter( 'pre_set_site_transient_update_plugins', [ $this, 'self_update_check' ] );
		add_filter( 'plugins_api', [ $this, 'self_plugins_api' ], 10, 3 );
	}

	// --------------------------------------------------------
	// Mu-plugin: bypass maintenance mode for our REST namespace
	// --------------------------------------------------------

	/**
	 * Create the mu-plugin file if it does not already exist.
	 * Called on plugins_loaded so it self-heals after plugin updates.
	 */
	public function ensure_mu_plugin(): void {
		$mu_dir  = defined( 'WPMU_PLUGIN_DIR' ) ? WPMU_PLUGIN_DIR : WP_CONTENT_DIR . '/mu-plugins';
		$mu_file = $mu_dir . DIRECTORY_SEPARATOR . self::MU_PLUGIN_FILE;

		if ( file_exists( $mu_file ) ) {
			return;
		}

		if ( ! is_dir( $mu_dir ) ) {
			wp_mkdir_p( $mu_dir );
		}

		$rest_ns  = STUH_REST_NS;
		$contents = <<<PHP
<?php
/**
 * Auto-generated by Switch Theme Updater Host.
 * Bypasses WordPress maintenance mode for the STU Host REST API so that
 * client update requests are served even while the host is updating itself.
 *
 * Do not edit — this file is recreated automatically.
 */
add_filter( 'wp_maintenance', static function ( bool \$enabled ): bool {
	if ( ! \$enabled ) {
		return false;
	}
	\$uri = \$_SERVER['REQUEST_URI'] ?? '';
	if ( str_contains( \$uri, '/wp-json/{$rest_ns}/' ) ) {
		return false;
	}
	return \$enabled;
} );
PHP;

		file_put_contents( $mu_file, $contents ); // phpcs:ignore WordPress.WP.AlternativeFunctions
	}

	/**
	 * Remove the mu-plugin file when this plugin is deactivated.
	 */
	public static function remove_mu_plugin(): void {
		$mu_dir  = defined( 'WPMU_PLUGIN_DIR' ) ? WPMU_PLUGIN_DIR : WP_CONTENT_DIR . '/mu-plugins';
		$mu_file = $mu_dir . DIRECTORY_SEPARATOR . self::MU_PLUGIN_FILE;
		if ( file_exists( $mu_file ) ) {
			unlink( $mu_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}
	}

	// --------------------------------------------------------
	// Self-upgrade: bypass maintenance mode by downloading
	// directly from GitHub instead of via our own REST API
	// --------------------------------------------------------

	/**
	 * Intercepts the WordPress plugin upgrader before it makes an HTTP request
	 * to download this plugin's own zip (which would hit this server while it is
	 * in maintenance mode and return a 503).
	 *
	 * When the plugin being upgraded is this one, we parse the REST API URL that
	 * the client plugin placed in the update transient, extract the repo/ref/path
	 * parameters, and download the zip directly from GitHub — staying entirely
	 * within the current PHP process.
	 *
	 * Priority 5 (lower than the client plugin's filter at 10) ensures we run
	 * first. If another filter already handled the download we pass through.
	 *
	 * @param false|string|\WP_Error $reply      The current reply (false = not yet handled).
	 * @param string                 $package    The package URL from the update transient.
	 * @param \WP_Upgrader           $upgrader   The upgrader instance.
	 * @param array                  $hook_extra Extra args (includes 'plugin' key for plugin upgrades).
	 * @return false|string|\WP_Error  Local temp-file path on success; false to pass through.
	 */
	public function intercept_self_upgrade( $reply, $package, $upgrader, $hook_extra ) {
		// Already handled by another filter — pass through.
		if ( false !== $reply ) {
			return $reply;
		}

		// Only intercept updates for this plugin itself.
		// Other plugins updated via the REST endpoint (e.g. themes/plugins on client sites
		// that happen to share this host) are left to the client plugin's own filter.
		$upgrading_plugin = $hook_extra['plugin'] ?? '';
		if ( $upgrading_plugin !== $this->self_plugin_basename() ) {
			return false;
		}

		// Confirm the download URL actually points to our own REST API endpoint.
		if ( ! str_contains( $package, '/wp-json/' . STUH_REST_NS . '/download' ) ) {
			return false;
		}

		// Parse repo/ref/path/pack from the REST API URL:
		//   https://host.test/wp-json/stu-host/v1/download?repo=owner/repo&ref=v1.2&path=/&pack=slug
		$parsed = wp_parse_url( $package );
		if ( empty( $parsed['query'] ) ) {
			return false; // Unexpected format — let WordPress handle it normally.
		}

		wp_parse_str( $parsed['query'], $params );
		$repo = sanitize_text_field( $params['repo'] ?? '' );
		$ref  = sanitize_text_field( $params['ref']  ?? '' );
		$path = sanitize_text_field( $params['path'] ?? '/' );
		$pack = sanitize_file_name( $params['pack'] ?? basename( $repo ) );

		if ( ! $repo || ! $ref ) {
			return false;
		}

		// Download straight from GitHub — no HTTP request to this server.
		return $this->github()->download_zipball( $repo, $ref, $path, $pack );
	}

	// --------------------------------------------------------
	// Self-update: version check + download directly from GitHub
	// --------------------------------------------------------

	/** Slug used in WordPress's update transient. */
	private function self_plugin_basename(): string {
		// Use the WP_PLUGIN_DIR-relative path WordPress registered this plugin under.
		// plugin_basename() resolves symlinks, so we derive it from the registered slug
		// via the plugin headers instead.
		return plugin_basename( __FILE__ );
	}

	/** The GitHub repo this plugin lives in (from plugin header). */
	private function self_github_repo(): string {
		return 'Team-Switch-Reclamebureau/switch-theme-updater-host';
	}

	/**
	 * Checks GitHub for a newer release and, if found, injects an update record
	 * into the WordPress update transient so the Dashboard shows the update.
	 */
	public function self_update_check( $transient ) {
		if ( empty( $transient->checked ) ) {
			return $transient;
		}

		$slug     = $this->self_plugin_basename();
		$current  = $transient->checked[ $slug ] ?? '0.0.0';
		$repo     = $this->self_github_repo();
		$gh       = $this->github();
		$result   = $gh->get_latest_version( $repo, null, '/', 'releases' );

		if ( ! $result || empty( $result['version'] ) || empty( $result['ref'] ) ) {
			return $transient;
		}

		if ( version_compare( $result['version'], $current, '<=' ) ) {
			return $transient;
		}

		// Build a download URL that points to our own REST endpoint —
		// intercept_self_upgrade will catch it and download from GitHub directly.
		$pack        = 'switch-theme-updater-host';
		$download    = add_query_arg(
			[
				'repo' => $repo,
				'ref'  => $result['ref'],
				'path' => '/',
				'pack' => $pack,
			],
			get_rest_url( null, STUH_REST_NS . '/download' )
		);

		$transient->response[ $slug ] = (object) [
			'slug'        => dirname( $slug ),
			'plugin'      => $slug,
			'new_version' => $result['version'],
			'package'     => $download,
			'url'         => 'https://github.com/' . $repo,
		];

		return $transient;
	}

	/**
	 * Supplies plugin information for the "View details" modal in wp-admin.
	 */
	public function self_plugins_api( $result, $action, $args ) {
		if ( 'plugin_information' !== $action ) {
			return $result;
		}
		if ( ( $args->slug ?? '' ) !== dirname( $this->self_plugin_basename() ) ) {
			return $result;
		}

		$repo   = $this->self_github_repo();
		$latest = $this->github()->get_latest_version( $repo, null, '/', 'releases' );

		return (object) [
			'name'          => 'Team Switch - Theme Updater Host',
			'slug'          => dirname( $this->self_plugin_basename() ),
			'version'       => $latest['version'] ?? '',
			'author'        => 'Team Switch',
			'homepage'      => 'https://github.com/' . $repo,
			'download_link' => add_query_arg(
				[
					'repo' => $repo,
					'ref'  => $latest['ref'] ?? '',
					'path' => '/',
					'pack' => 'switch-theme-updater-host',
				],
				get_rest_url( null, STUH_REST_NS . '/download' )
			),
			'sections'      => [
				'description' => 'Central update proxy. Authenticates client sites and relays GitHub releases without exposing the GitHub token.',
			],
		];
	}

	public function maybe_notice_no_token(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}
		$s     = self::get_settings();
		$token = defined( 'STUH_TOKEN' ) ? STUH_TOKEN : ( $s['token'] ?? '' );
		if ( $token ) {
			return;
		}
		$url = admin_url( 'admin.php?page=stuh-settings' );
		echo '<div class="notice notice-error"><p>';
		echo '<strong>Switch Updater Host:</strong> No GitHub token is configured. ';
		echo 'Client sites will not be able to fetch updates until a token is added. ';
		echo '<a href="' . esc_url( $url ) . '">Configure now &rarr;</a>';
		echo '</p></div>';
	}

	// --------------------------------------------------------
	// Data helpers
	// --------------------------------------------------------

	public static function get_settings(): array {
		$opt = get_option( STUH_OPTION_SETTINGS, [] );
		return wp_parse_args( $opt, [ 'token' => '', 'allow_unverified' => false ] );
	}

	public static function get_clients(): array {
		return (array) get_option( STUH_OPTION_CLIENTS, [] );
	}

	private static function save_clients( array $clients ): void {
		update_option( STUH_OPTION_CLIENTS, array_values( $clients ) );
	}

	public static function get_unverified(): array {
		return (array) get_option( STUH_OPTION_UNVERIFIED, [] );
	}

	private static function save_unverified( array $records ): void {
		update_option( STUH_OPTION_UNVERIFIED, array_values( $records ) );
	}

	public static function get_whitelist(): array {
		return (array) get_option( STUH_OPTION_WHITELIST, [] );
	}

	private static function save_whitelist( array $entries ): void {
		update_option( STUH_OPTION_WHITELIST, array_values( $entries ) );
	}

	/**
	 * Returns true if the given IP is in the whitelist.
	 */
	public static function ip_is_whitelisted( string $ip ): bool {
		foreach ( self::get_whitelist() as $entry ) {
			if ( ( $entry['ip'] ?? '' ) === $ip ) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Record an unauthenticated or invalid-key request.
	 * Deduplicates by IP; throttles DB writes to once per 5 minutes per IP.
	 *
	 * @param WP_REST_Request $req  The failed request.
	 * @param string          $reason  'missing_key' or 'invalid_key'.
	 */
	public static function record_unverified( WP_REST_Request $req, string $reason ): void {
		$ip       = sanitize_text_field( $_SERVER['REMOTE_ADDR'] ?? '' );
		$endpoint = sanitize_text_field( $req->get_route() );

		// Try to parse the WordPress site URL from the User-Agent.
		// WordPress sets UA like: "WordPress/6.5; https://example.com"
		$ua       = sanitize_text_field( $_SERVER['HTTP_USER_AGENT'] ?? '' );
		$site_url = '';
		if ( preg_match( '#WordPress/[\d.]+;\s*(https?://[^\s]+)#i', $ua, $m ) ) {
			$site_url = self::strip_language_prefix( esc_url_raw( rtrim( $m[1], '/' ) ) );
		}

		if ( ! $ip ) {
			return;
		}

		$records = self::get_unverified();
		$now     = time();
		$found   = false;

		foreach ( $records as &$r ) {
			if ( $r['ip'] !== $ip ) {
				continue;
			}
			$found = true;
			$r['attempts']++;
			$r['last_reason'] = $reason;
			$r['last_endpoint'] = $endpoint;
			if ( $site_url ) {
				$r['site_url'] = $site_url;
			}
			// Throttle write: only update last_seen once per 5 minutes.
			if ( ( $now - ( $r['last_seen'] ?? 0 ) ) > 300 ) {
				$r['last_seen'] = $now;
				self::save_unverified( $records );
			}
			break;
		}
		unset( $r );

		if ( ! $found ) {
			$records[] = [
				'id'            => uniqid( 'stuh_uv_', true ),
				'ip'            => $ip,
				'site_url'      => $site_url,
				'first_seen'    => $now,
				'last_seen'     => $now,
				'attempts'      => 1,
				'last_reason'   => $reason,
				'last_endpoint' => $endpoint,
			];
			self::save_unverified( $records );

			// Notify on first sighting of this IP.
			$display    = $site_url ?: $ip;
			$admin_url  = admin_url( 'admin.php?page=stuh' );
			wp_mail(
				'online@teamswitch.nl',
				sprintf( '[teamswitch.dev] New unverified access attempt from %s', $display ),
				sprintf(
					"A new unverified access attempt was recorded.\n\n" .
					"IP address : %s\n" .
					"Site URL   : %s\n" .
					"Endpoint   : %s\n" .
					"Reason     : %s\n\n" .
					"Review and allow or dismiss in wp-admin:\n%s",
					$ip,
					$site_url ?: '(unknown)',
					$endpoint,
					$reason,
					$admin_url
				)
			);
		}
	}

	// --------------------------------------------------------
	// Authentication
	// --------------------------------------------------------

	/**
	 * Strip a WPML-style language-code path segment from a site URL so that
	 * https://example.com/en and https://example.com are treated as the same site.
	 * Only a single path segment that is 2-3 ASCII alpha characters is removed;
	 * subdirectory installs (e.g. https://example.com/blog) are left untouched.
	 */
	private static function strip_language_prefix( string $url ): string {
		$parsed = wp_parse_url( $url );
		if ( empty( $parsed['host'] ) ) {
			return $url;
		}
		$path = trim( $parsed['path'] ?? '', '/' );
		// Strip only when the whole path looks like a 2- or 3-letter ISO language code.
		if ( $path !== '' && preg_match( '#^[a-z]{2,3}$#i', $path ) ) {
			$clean = ( $parsed['scheme'] ?? 'https' ) . '://' . $parsed['host'];
			if ( ! empty( $parsed['port'] ) ) {
				$clean .= ':' . $parsed['port'];
			}
			return $clean;
		}
		return $url;
	}

	/**
	 * Validate a raw API key against stored (hashed) client records.
	 * Updates last_seen at most once per 5 minutes to reduce DB writes.
	 *
	 * @param string $raw_key  The plaintext key sent by the client.
	 * @return array|false     The matching client record, or false on failure.
	 */
	public static function authenticate_client( string $raw_key, string $site_url = '' ) {
		if ( empty( $raw_key ) ) {
			return false;
		}

		$clients = self::get_clients();
		$matched = false;
		$idx     = null;

		// Normalise the incoming URL for comparison (lowercase, no trailing slash).
		$norm_url = strtolower( rtrim( $site_url, '/' ) );

		foreach ( $clients as $i => $client ) {
			if ( ! ( $client['enabled'] ?? true ) ) {
				continue;
			}
			if ( ! wp_check_password( $raw_key, $client['api_key_hash'] ) ) {
				continue;
			}
			// Key matches — now verify the site URL if one is stored.
			$stored_url = strtolower( rtrim( $client['site_url'] ?? '', '/' ) );
			if ( $stored_url !== '' && $stored_url !== $norm_url ) {
				// Key is valid but the URL doesn't match — reject.
				return false;
			}
			$matched = $client;
			$idx     = $i;
			break;
		}

		if ( false === $matched ) {
			return false;
		}

		// Throttle last_seen writes to once per 5 minutes.
		$last = $matched['last_seen'] ?? 0;
		if ( ( time() - $last ) > 300 ) {
			$clients[ $idx ]['last_seen']    = time();
			$clients[ $idx ]['last_seen_ip'] = sanitize_text_field( $_SERVER['REMOTE_ADDR'] ?? '' );
			self::save_clients( $clients );
		}

		return $matched;
	}

	// --------------------------------------------------------
	// REST API registration
	// --------------------------------------------------------

	public function register_rest_routes(): void {
		$auth = [ $this, 'rest_permission' ];

		register_rest_route( STUH_REST_NS, '/version', [
			'methods'             => WP_REST_Server::READABLE,
			'callback'            => [ $this, 'rest_version' ],
			'permission_callback' => $auth,
			'args'                => [
				'repo'   => [ 'required' => true,  'sanitize_callback' => 'sanitize_text_field' ],
				'mode'   => [ 'default'  => 'releases', 'sanitize_callback' => 'sanitize_text_field' ],
				'branch' => [ 'default'  => 'main', 'sanitize_callback' => 'sanitize_text_field' ],
				'ref'    => [ 'default'  => '',    'sanitize_callback' => 'sanitize_text_field' ],
				'path'   => [ 'default'  => '/',   'sanitize_callback' => 'sanitize_text_field' ],
			],
		] );

		register_rest_route( STUH_REST_NS, '/releases', [
			'methods'             => WP_REST_Server::READABLE,
			'callback'            => [ $this, 'rest_releases' ],
			'permission_callback' => $auth,
			'args'                => [
				'repo' => [ 'required' => true, 'sanitize_callback' => 'sanitize_text_field' ],
			],
		] );

		register_rest_route( STUH_REST_NS, '/validate', [
			'methods'             => WP_REST_Server::READABLE,
			'callback'            => [ $this, 'rest_validate' ],
			'permission_callback' => '__return_true',
		] );

		register_rest_route( STUH_REST_NS, '/download', [
			'methods'             => WP_REST_Server::READABLE,
			'callback'            => [ $this, 'rest_download' ],
			'permission_callback' => $auth,
			'args'                => [
				'repo' => [ 'required' => true,  'sanitize_callback' => 'sanitize_text_field' ],
				'ref'  => [ 'required' => true,  'sanitize_callback' => 'sanitize_text_field' ],
				'path' => [ 'default'  => '/',   'sanitize_callback' => 'sanitize_text_field' ],
				'pack' => [ 'default'  => '',    'sanitize_callback' => 'sanitize_text_field' ],
			],
		] );
	}

	// --------------------------------------------------------
	// REST permission callback (shared by all endpoints)
	// --------------------------------------------------------

	public function rest_permission( WP_REST_Request $req ) {
		$s    = self::get_settings();
		$key  = $req->get_header( 'X-STU-Key' );
		$ip   = sanitize_text_field( $_SERVER['REMOTE_ADDR'] ?? '' );

		// Whitelisted IPs always pass through, no key required.
		if ( $ip && self::ip_is_whitelisted( $ip ) ) {
			return true;
		}

		// Extract the site URL from the WordPress User-Agent header.
		// WP sends: "WordPress/6.5; https://example.com"
		$ua       = sanitize_text_field( $_SERVER['HTTP_USER_AGENT'] ?? '' );
		$site_url = '';
		if ( preg_match( '#WordPress/[\d.]+;\s*(https?://[^\s]+)#i', $ua, $m ) ) {
			$site_url = self::strip_language_prefix( esc_url_raw( rtrim( $m[1], '/' ) ) );
		}

		// Detect requests originating from this site itself (e.g. self-update).
		// Loopback IPs or a User-Agent site URL matching home_url() both count.
		$home      = rtrim( home_url(), '/' );
		$is_self   = in_array( $ip, [ '127.0.0.1', '::1' ], true )
		             || ( $site_url && $site_url === $home );

		if ( empty( $key ) ) {
			if ( ! $is_self ) {
				self::record_unverified( $req, 'missing_key' );
			}
			if ( ! empty( $s['allow_unverified'] ) ) {
				return true;
			}
			return new WP_Error( 'missing_key', 'API key required', [ 'status' => 401 ] );
		}

		if ( ! self::authenticate_client( $key, $site_url ) ) {
			if ( ! $is_self ) {
				self::record_unverified( $req, 'invalid_key' );
			}
			if ( ! empty( $s['allow_unverified'] ) ) {
				return true;
			}
			return new WP_Error( 'invalid_key', 'Invalid or disabled API key', [ 'status' => 403 ] );
		}
		return true;
	}

	// --------------------------------------------------------
	// REST endpoint: validate licence / API key
	// --------------------------------------------------------

	public function rest_validate( WP_REST_Request $req ) {
		$ip = sanitize_text_field( $_SERVER['REMOTE_ADDR'] ?? '' );

		// Whitelisted IPs are always valid, no key required.
		if ( $ip && self::ip_is_whitelisted( $ip ) ) {
			return rest_ensure_response( [
				'valid'  => true,
				'method' => 'ip_whitelist',
			] );
		}

		$key      = $req->get_header( 'X-STU-Key' );
		$ua       = sanitize_text_field( $_SERVER['HTTP_USER_AGENT'] ?? '' );
		$site_url = '';
		if ( preg_match( '#WordPress/[\d.]+;\s*(https?://[^\s]+)#i', $ua, $m ) ) {
			$site_url = self::strip_language_prefix( esc_url_raw( rtrim( $m[1], '/' ) ) );
		}

		$client = $key ? self::authenticate_client( $key, $site_url ) : false;

		if ( $client ) {
			error_log( sprintf( '[STUH validate] PASS api_key | ip=%s site=%s', $ip, $client['site_url'] ?? $site_url ) ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
			return rest_ensure_response( [
				'valid'    => true,
				'method'   => 'api_key',
				'site_url' => $client['site_url'] ?? '',
			] );
		}

		// Determine whether this is a self-request (same logic as rest_permission).
		$home    = rtrim( home_url(), '/' );
		$is_self = ( $site_url && $site_url === $home );

		$reason = $key ? 'invalid_key' : 'missing_key';
		error_log( sprintf( '[STUH validate] FAIL %s | ip=%s site=%s self=%s', $reason, $ip, $site_url ?: '(unknown)', $is_self ? 'yes' : 'no' ) ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log

		if ( ! $is_self ) {
			self::record_unverified( $req, $reason );
		}

		// allow_unverified let this request through, but the licence is not valid.
		return rest_ensure_response( [ 'valid' => false ] );
	}

	// --------------------------------------------------------
	// REST endpoint: latest version
	// --------------------------------------------------------

	public function rest_version( WP_REST_Request $req ) {
		$repo   = $req->get_param( 'repo' );
		$mode   = $req->get_param( 'mode' );
		$branch = $req->get_param( 'branch' );
		$ref    = $req->get_param( 'ref' );
		$path   = $req->get_param( 'path' );

		if ( ! $this->valid_repo( $repo ) ) {
			return new WP_Error( 'invalid_repo', 'Invalid repository format (expected owner/repo)', [ 'status' => 400 ] );
		}

		$gh = $this->github();

		if ( 'tag' === $mode && $ref ) {
			$result = $gh->get_version_from_tag( $repo, $ref, $path );
		} elseif ( 'commits' === $mode ) {
			$result = $gh->get_latest_version( $repo, $branch, $path, 'commits' );
		} else {
			$result = $gh->get_latest_version( $repo, null, $path, 'releases' );
		}

		if ( ! $result ) {
			return new WP_Error( 'no_version', 'No version found for this repository', [ 'status' => 404 ] );
		}

		return rest_ensure_response( $result );
	}

	// --------------------------------------------------------
	// REST endpoint: list releases
	// --------------------------------------------------------

	public function rest_releases( WP_REST_Request $req ) {
		$repo = $req->get_param( 'repo' );

		if ( ! $this->valid_repo( $repo ) ) {
			return new WP_Error( 'invalid_repo', 'Invalid repository format', [ 'status' => 400 ] );
		}

		$releases = $this->github()->get_releases( $repo );
		return rest_ensure_response( [ 'releases' => $releases ] );
	}

	// --------------------------------------------------------
	// REST endpoint: download zip (binary stream – exits early)
	// --------------------------------------------------------

	public function rest_download( WP_REST_Request $req ): void {
		$repo = $req->get_param( 'repo' );
		$ref  = $req->get_param( 'ref' );
		$path = $req->get_param( 'path' );
		$pack = $req->get_param( 'pack' ) ?: basename( $repo );

		if ( ! $this->valid_repo( $repo ) ) {
			wp_send_json_error( [ 'message' => 'Invalid repository format' ], 400 );
		}

		$zip = $this->github()->download_zipball( $repo, $ref, $path, $pack );

		if ( is_wp_error( $zip ) ) {
			wp_send_json_error( [ 'message' => $zip->get_error_message() ], 502 );
		}

		// Stream binary zip to the client site.
		header( 'Content-Type: application/zip' );
		header( 'Content-Disposition: attachment; filename="' . sanitize_file_name( $pack ) . '.zip"' );
		header( 'Content-Length: ' . filesize( $zip ) );
		header( 'Cache-Control: no-store' );
		readfile( $zip ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_read_readfile
		@unlink( $zip );  // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		exit;
	}

	// --------------------------------------------------------
	// Internal helpers
	// --------------------------------------------------------

	private function valid_repo( string $repo ): bool {
		return (bool) preg_match( '/^[a-zA-Z0-9_.\-]+\/[a-zA-Z0-9_.\-]+$/', $repo );
	}

	private function github(): STUH_GitHubClient {
		static $gh = null;
		if ( $gh ) {
			return $gh;
		}
		$s     = self::get_settings();
		$token = defined( 'STUH_TOKEN' ) ? STUH_TOKEN : ( $s['token'] ?? '' );
		$gh    = new STUH_GitHubClient( $token, 'https://api.github.com' );
		return $gh;
	}

	// --------------------------------------------------------
	// Admin menus
	// --------------------------------------------------------

	public function register_admin_menu(): void {
		add_menu_page(
			__( 'Switch Updater Host', 'stuh' ),
			__( 'Updater Host', 'stuh' ),
			'manage_options',
			'stuh',
			[ $this, 'render_clients_page' ],
			'dashicons-cloud',
			59
		);
		add_submenu_page(
			'stuh',
			__( 'Client Sites', 'stuh' ),
			__( 'Client Sites', 'stuh' ),
			'manage_options',
			'stuh',
			[ $this, 'render_clients_page' ]
		);
		add_submenu_page(
			'stuh',
			__( 'Settings', 'stuh' ),
			__( 'Settings', 'stuh' ),
			'manage_options',
			'stuh-settings',
			[ $this, 'render_settings_page' ]
		);
	}

	// --------------------------------------------------------
	// Admin action handler (POST handler for all admin forms)
	// --------------------------------------------------------

	public function handle_admin_actions(): void {
		if ( empty( $_POST['stuh_action'] ) || ! current_user_can( 'manage_options' ) ) {
			return;
		}
		check_admin_referer( 'stuh_admin' );

		$action  = sanitize_key( $_POST['stuh_action'] );
		$clients = self::get_clients();

		switch ( $action ) {

			case 'add_client':
				$url = esc_url_raw( trim( $_POST['site_url'] ?? '' ) );
				if ( $url ) {
					$raw_key   = bin2hex( random_bytes( 24 ) ); // 48 hex chars, 192 bits
					$clients[] = [
						'id'           => uniqid( 'stuh_', true ),
						'site_url'     => $url,
						'api_key'      => $raw_key,
						'api_key_hash' => wp_hash_password( $raw_key ),
						'enabled'      => true,
						'created_at'   => time(),
						'last_seen'    => null,
						'last_seen_ip' => null,
					];
					self::save_clients( $clients );
					set_transient(
						'stuh_new_key_' . get_current_user_id(),
						[ 'key' => $raw_key, 'site' => $url ],
						120 // shown for 2 minutes max
					);
				}
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;

			case 'toggle_client':
				$id = sanitize_text_field( $_POST['client_id'] ?? '' );
				foreach ( $clients as &$c ) {
					if ( $c['id'] === $id ) {
						$c['enabled'] = ! ( $c['enabled'] ?? true );
						break;
					}
				}
				unset( $c );
				self::save_clients( $clients );
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;

			case 'delete_client':
				$id      = sanitize_text_field( $_POST['client_id'] ?? '' );
				$clients = array_values( array_filter( $clients, fn( $c ) => $c['id'] !== $id ) );
				self::save_clients( $clients );
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;

			case 'regenerate_key':
				$id       = sanitize_text_field( $_POST['client_id'] ?? '' );
				$site_url = '';
				foreach ( $clients as &$c ) {
					if ( $c['id'] === $id ) {
						$raw_key          = bin2hex( random_bytes( 24 ) );
						$c['api_key_hash'] = wp_hash_password( $raw_key );
						$site_url          = $c['site_url'];
						break;
					}
				}
				unset( $c );
				self::save_clients( $clients );
				if ( $site_url ) {
					set_transient(
						'stuh_new_key_' . get_current_user_id(),
						[ 'key' => $raw_key, 'site' => $site_url ],
						120
					);
				}
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;

			case 'save_settings':
				$token            = sanitize_text_field( $_POST['token'] ?? '' );
				$allow_unverified = ! empty( $_POST['allow_unverified'] );
				update_option( STUH_OPTION_SETTINGS, [ 'token' => $token, 'allow_unverified' => $allow_unverified ] );
				wp_safe_redirect( add_query_arg( 'stuh_saved', '1', admin_url( 'admin.php?page=stuh-settings' ) ) );
				exit;

			case 'check_for_updates':
				// Delete the cached transient so WordPress re-checks immediately.
				delete_site_transient( 'update_plugins' );
				// Trigger the check synchronously so the result is ready when we redirect.
				wp_update_plugins();
				$slug    = plugin_basename( __FILE__ );
				$updates = get_site_transient( 'update_plugins' );
				if ( isset( $updates->response[ $slug ] ) ) {
					$status = 'update_available';
				} else {
					$status = 'up_to_date';
				}
				wp_safe_redirect( add_query_arg( 'stuh_update_check', $status, admin_url( 'admin.php?page=stuh-settings' ) ) );
				exit;

			case 'delete_unverified':
				$id      = sanitize_text_field( $_POST['unverified_id'] ?? '' );
				$records = array_values( array_filter( self::get_unverified(), fn( $r ) => $r['id'] !== $id ) );
				self::save_unverified( $records );
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;

			case 'clear_unverified':
				delete_option( STUH_OPTION_UNVERIFIED );
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;

			case 'add_whitelist':
				$wl_ip   = sanitize_text_field( trim( $_POST['wl_ip']   ?? '' ) );
				$wl_name = sanitize_text_field( trim( $_POST['wl_name'] ?? '' ) );
				if ( $wl_ip && $wl_name ) {
					// Basic IP validation (IPv4 and IPv6).
					if ( filter_var( $wl_ip, FILTER_VALIDATE_IP ) ) {
						$whitelist   = self::get_whitelist();
						$whitelist[] = [
							'id'         => uniqid( 'stuh_wl_', true ),
							'ip'         => $wl_ip,
							'label'      => $wl_name,
							'created_at' => time(),
						];
						self::save_whitelist( $whitelist );
					}
				}
				wp_safe_redirect( admin_url( 'admin.php?page=stuh-settings' ) );
				exit;

			case 'delete_whitelist':
				$wl_id     = sanitize_text_field( $_POST['wl_id'] ?? '' );
				$whitelist = array_values( array_filter( self::get_whitelist(), fn( $e ) => $e['id'] !== $wl_id ) );
				self::save_whitelist( $whitelist );
				wp_safe_redirect( admin_url( 'admin.php?page=stuh-settings' ) );
				exit;

			case 'promote_unverified':
				$id      = sanitize_text_field( $_POST['unverified_id'] ?? '' );
				$records = self::get_unverified();
				$entry   = null;
				foreach ( $records as $r ) {
					if ( $r['id'] === $id ) { $entry = $r; break; }
				}
				if ( $entry ) {
					$raw_key = bin2hex( random_bytes( 24 ) );
					$clients = self::get_clients();
					$clients[] = [
						'id'           => uniqid( 'stuh_', true ),
						'site_url'     => $entry['site_url'] ?: '',
						'api_key'      => $raw_key,
						'api_key_hash' => wp_hash_password( $raw_key ),
						'enabled'      => true,
						'created_at'   => time(),
						'last_seen'    => null,
						'last_seen_ip' => null,
					];
					self::save_clients( $clients );
					// Remove from unverified.
					$records = array_values( array_filter( $records, fn( $r ) => $r['id'] !== $id ) );
					self::save_unverified( $records );
					set_transient(
						'stuh_new_key_' . get_current_user_id(),
						[ 'key' => $raw_key, 'site' => $entry['site_url'] ?: $entry['ip'] ],
						120
					);
				}
				wp_safe_redirect( admin_url( 'admin.php?page=stuh' ) );
				exit;
		}
	}

	// --------------------------------------------------------
	// Admin page: client site list
	// --------------------------------------------------------

	public function render_clients_page(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Insufficient permissions', 'stuh' ) );
		}

		$clients = self::get_clients();
		$uid     = get_current_user_id();
		$new_key = get_transient( 'stuh_new_key_' . $uid );
		if ( $new_key ) {
			delete_transient( 'stuh_new_key_' . $uid );
		}
		?>
		<div class="wrap">
			<h1><?php esc_html_e( 'Switch Updater Host — Client Sites', 'stuh' ); ?></h1>

			<?php if ( $new_key ) : ?>
			<div class="notice notice-success" style="padding: 16px 16px 8px;">
				<h3 style="margin-top: 0;">&#128274; New API Key</h3>
				<p><strong>This key is shown only once. Copy it before leaving this page.</strong></p>
				<code id="stuh-api-key" style="display:block;font-size:14px;background:#f0f0f1;padding:10px 14px;border-radius:4px;word-break:break-all;user-select:all;margin-bottom:12px;"><?php echo esc_html( $new_key['key'] ); ?></code>
			</div>
			<?php endif; ?>

			<?php
			// Sorting.
			$allowed_cols = [ 'site_url', 'enabled', 'created_at', 'last_seen' ];
			$orderby      = in_array( $_GET['orderby'] ?? '', $allowed_cols, true ) ? $_GET['orderby'] : 'site_url';
			$order        = strtolower( $_GET['order'] ?? 'asc' ) === 'desc' ? 'desc' : 'asc';
			$opposite     = $order === 'asc' ? 'desc' : 'asc';

			usort( $clients, function( $a, $b ) use ( $orderby, $order ) {
				$va = $a[ $orderby ] ?? '';
				$vb = $b[ $orderby ] ?? '';
				// Nulls last.
				if ( $va === null || $va === '' ) return $order === 'asc' ? 1 : -1;
				if ( $vb === null || $vb === '' ) return $order === 'asc' ? -1 : 1;
				$cmp = is_numeric( $va ) ? ( $va <=> $vb ) : strcasecmp( (string) $va, (string) $vb );
				return $order === 'asc' ? $cmp : -$cmp;
			} );

			$sort_url = function( string $col ) use ( $orderby, $order, $opposite ): string {
				return esc_url( add_query_arg( [
					'page'    => 'stuh',
					'orderby' => $col,
					'order'   => $orderby === $col ? $opposite : 'asc',
				], admin_url( 'admin.php' ) ) );
			};
			$sort_indicator = function( string $col ) use ( $orderby, $order ): string {
				if ( $orderby !== $col ) return '';
				return ' <span class="dashicons dashicons-arrow-' . ( $order === 'asc' ? 'up' : 'down' ) . '" style="vertical-align:middle;font-size:14px;"></span>';
			};
			?>

			<table class="wp-list-table widefat fixed striped" style="margin-top: 20px;">
				<thead>
					<tr>
						<th scope="col" style="width: 15%;">
							<a href="<?php echo $sort_url( 'site_url' ); ?>">URL<?php echo $sort_indicator( 'site_url' ); ?></a>
						</th>
						<th scope="col" style="width: 8%;">
							<a href="<?php echo $sort_url( 'enabled' ); ?>">Status<?php echo $sort_indicator( 'enabled' ); ?></a>
						</th>
						<th scope="col" style="width: 8%;">
							<a href="<?php echo $sort_url( 'created_at' ); ?>">Created<?php echo $sort_indicator( 'created_at' ); ?></a>
						</th>
						<th scope="col" style="width: 12%;">
							<a href="<?php echo $sort_url( 'last_seen' ); ?>">Last Seen<?php echo $sort_indicator( 'last_seen' ); ?></a>
						</th>
						<th scope="col" style="width: 25%;">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php if ( empty( $clients ) ) : ?>
					<tr>
						<td colspan="5" style="padding: 16px;">
							<em><?php esc_html_e( 'No client sites registered yet. Add one below.', 'stuh' ); ?></em>
						</td>
					</tr>
					<?php else : ?>
					<?php foreach ( $clients as $c ) :
						$enabled = (bool) ( $c['enabled'] ?? true );
					?>
					<tr>
						<td>
							<a href="<?php echo esc_url( $c['site_url'] ); ?>" target="_blank" rel="noopener">
								<?php echo esc_html( preg_replace( '#^https?://#', '', $c['site_url'] ) ); ?>
							</a>
						</td>
						<td>
							<?php if ( $enabled ) : ?>
								<span style="color:#46b450;font-weight:600;">&#10003; Active</span>
							<?php else : ?>
								<span style="color:#d63638;font-weight:600;">&#10005; Disabled</span>
							<?php endif; ?>
						</td>
						<td>
							<?php echo esc_html( $c['created_at'] ? date_i18n( 'Y-m-d', $c['created_at'] ) : '—' ); ?>
						</td>
						<td>
							<?php if ( $c['last_seen'] ) : ?>
								<?php echo esc_html( date_i18n( 'Y-m-d H:i', $c['last_seen'] ) ); ?><br>
								<small><?php echo esc_html( $c['last_seen_ip'] ?? '' ); ?></small>
							<?php else : ?>
								<em>Never</em>
							<?php endif; ?>
						</td>
						<td style="white-space: nowrap;">
							<!-- Enable / Disable -->
							<form method="post" style="display:inline-block;margin-right:4px;">
								<?php wp_nonce_field( 'stuh_admin' ); ?>
								<input type="hidden" name="stuh_action" value="toggle_client">
								<input type="hidden" name="client_id" value="<?php echo esc_attr( $c['id'] ); ?>">
								<button type="submit" class="button button-secondary">
									<?php echo $enabled ? esc_html__( 'Disable', 'stuh' ) : esc_html__( 'Enable', 'stuh' ); ?>
								</button>
							</form>
							<?php if ( ! empty( $c['api_key'] ) ) : ?>
							<!-- Copy Key -->
							<button type="button" class="button" style="margin-right:4px;"
									data-key="<?php echo esc_attr( $c['api_key'] ); ?>"
									onclick="(function(btn){
										navigator.clipboard.writeText(btn.dataset.key).then(function(){
											btn.textContent='Copied!';
											setTimeout(function(){ btn.textContent='Copy Key'; }, 2000);
										});
									})(this)">
								<?php esc_html_e( 'Copy Key', 'stuh' ); ?>
							</button>
							<?php endif; ?>
							<!-- Delete -->
							<form method="post" style="display:inline-block;"
								  onsubmit="return confirm('Permanently delete this client site?');">
								<?php wp_nonce_field( 'stuh_admin' ); ?>
								<input type="hidden" name="stuh_action" value="delete_client">
								<input type="hidden" name="client_id" value="<?php echo esc_attr( $c['id'] ); ?>">
								<button type="submit" class="button"
										style="color:#d63638;border-color:#d63638;">
									<?php esc_html_e( 'Delete', 'stuh' ); ?>
								</button>
							</form>
						</td>
					</tr>
					<?php endforeach; ?>
					<?php endif; ?>
				</tbody>
			</table>

		<?php
		$unverified = self::get_unverified();
		if ( ! empty( $unverified ) ) :
		?>
		<hr>
		<h2 style="color:#d63638;">&#9888; Unverified Access Attempts</h2>
		<p>These sites contacted the update host without a valid API key. You can grant them access by clicking <strong>Register &amp; Generate Key</strong>, or dismiss them.</p>
		<table class="wp-list-table widefat fixed striped">
			<thead>
				<tr>
					<th style="width:20%;">Detected Site URL</th>
					<th style="width:14%;">IP Address</th>
					<th style="width:10%;">Attempts</th>
					<th style="width:12%;">First Seen</th>
					<th style="width:12%;">Last Seen</th>
					<th style="width:14%;">Reason</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ( $unverified as $uv ) : ?>
				<tr>
					<td>
						<?php if ( $uv['site_url'] ) : ?>
							<a href="<?php echo esc_url( $uv['site_url'] ); ?>" target="_blank" rel="noopener">
								<?php echo esc_html( $uv['site_url'] ); ?>
							</a>
						<?php else : ?>
							<em>Unknown</em>
						<?php endif; ?>
					</td>
					<td><code><?php echo esc_html( $uv['ip'] ); ?></code></td>
					<td><?php echo (int) $uv['attempts']; ?></td>
					<td><?php echo esc_html( date_i18n( 'Y-m-d H:i', $uv['first_seen'] ) ); ?></td>
					<td><?php echo esc_html( date_i18n( 'Y-m-d H:i', $uv['last_seen'] ) ); ?></td>
					<td>
						<?php
						$reason_label = 'missing_key' === $uv['last_reason']
							? '<span title="No key was sent">No key</span>'
							: '<span title="A key was sent but did not match any registered site">Invalid key</span>';
						echo wp_kses( $reason_label, [ 'span' => [ 'title' => [] ] ] );
						?>
						<br><small><code><?php echo esc_html( $uv['last_endpoint'] ?? '' ); ?></code></small>
					</td>
					<td style="white-space:nowrap;">
						<!-- Promote to registered client -->
						<form method="post" style="display:inline-block;margin-right:4px;"
							  onsubmit="return confirm('Register this site and generate an API key?');">
							<?php wp_nonce_field( 'stuh_admin' ); ?>
							<input type="hidden" name="stuh_action" value="promote_unverified">
							<input type="hidden" name="unverified_id" value="<?php echo esc_attr( $uv['id'] ); ?>">
							<button type="submit" class="button button-primary">
								<?php esc_html_e( 'Register &amp; Generate Key', 'stuh' ); ?>
							</button>
						</form>
						<!-- Dismiss -->
						<form method="post" style="display:inline-block;">
							<?php wp_nonce_field( 'stuh_admin' ); ?>
							<input type="hidden" name="stuh_action" value="delete_unverified">
							<input type="hidden" name="unverified_id" value="<?php echo esc_attr( $uv['id'] ); ?>">
							<button type="submit" class="button" style="color:#d63638;border-color:#d63638;">
								<?php esc_html_e( 'Dismiss', 'stuh' ); ?>
							</button>
						</form>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
		<form method="post" style="margin-top:8px;"
			  onsubmit="return confirm('Clear all unverified records?');">
			<?php wp_nonce_field( 'stuh_admin' ); ?>
			<input type="hidden" name="stuh_action" value="clear_unverified">
			<button type="submit" class="button"><?php esc_html_e( 'Clear All Unverified', 'stuh' ); ?></button>
		</form>
		<?php endif; ?>

		<hr>
		<h2><?php esc_html_e( 'Add Client Site', 'stuh' ); ?></h2>
		<form method="post">
			<?php wp_nonce_field( 'stuh_admin' ); ?>
			<input type="hidden" name="stuh_action" value="add_client">
			<table class="form-table" role="presentation">
				<tr>
					<th scope="row">
						<label for="site_url"><?php esc_html_e( 'Site URL', 'stuh' ); ?></label>
					</th>
					<td>
						<input type="url" id="site_url" name="site_url"
							   class="regular-text" placeholder="https://example.com" required>
						<p class="description">
							<?php esc_html_e( 'Must match the WordPress site URL of the client. Used together with the API key to authenticate requests.', 'stuh' ); ?>
						</p>
					</td>
				</tr>
			</table>
			<?php submit_button( __( 'Add Site &amp; Generate Key', 'stuh' ) ); ?>
		</form>
	</div>
	<?php
	}

	// --------------------------------------------------------
	// Admin page: settings
	// --------------------------------------------------------

	public function render_settings_page(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Insufficient permissions', 'stuh' ) );
		}
		$s = self::get_settings();
		?>
		<div class="wrap">
			<h1><?php esc_html_e( 'Switch Updater Host — Settings', 'stuh' ); ?></h1>

			<?php if ( isset( $_GET['stuh_saved'] ) ) : ?>
			<div class="notice notice-success is-dismissible">
				<p><?php esc_html_e( 'Settings saved.', 'stuh' ); ?></p>
			</div>
			<?php endif; ?>

		<?php if ( isset( $_GET['stuh_update_check'] ) ) : ?>
			<?php if ( 'update_available' === $_GET['stuh_update_check'] ) : ?>
			<div class="notice notice-warning is-dismissible">
				<p>
					<?php esc_html_e( 'An update is available for Switch Updater Host.', 'stuh' ); ?>
					<a href="<?php echo esc_url( admin_url( 'update-core.php' ) ); ?>">
						<?php esc_html_e( 'Go to Updates &rarr;', 'stuh' ); ?>
					</a>
				</p>
			</div>
			<?php else : ?>
			<div class="notice notice-success is-dismissible">
				<p><?php esc_html_e( 'Switch Updater Host is up to date.', 'stuh' ); ?></p>
			</div>
			<?php endif; ?>
		<?php endif; ?>

			<form method="post">
				<?php wp_nonce_field( 'stuh_admin' ); ?>
				<input type="hidden" name="stuh_action" value="save_settings">
				<table class="form-table" role="presentation">
					<tr>
						<th scope="row">
							<label for="token"><?php esc_html_e( 'GitHub Personal Access Token', 'stuh' ); ?></label>
						</th>
						<td>
							<input type="password" id="token" name="token"
								   class="regular-text" value="<?php echo esc_attr( $s['token'] ?? '' ); ?>"
								   autocomplete="new-password">
							<p class="description">
								<?php esc_html_e( 'Token requires repo scope. Never stored in client sites.', 'stuh' ); ?>
							</p>
						</td>
					</tr>
					<tr>
						<th scope="row">
							<?php esc_html_e( 'Allow Unverified Updates', 'stuh' ); ?>
						</th>
						<td>
							<label>
								<input type="checkbox" name="allow_unverified" value="1"
									<?php checked( $s['allow_unverified'] ?? false ); ?>>
								<?php esc_html_e( 'Allow sites without a registered API key to fetch updates', 'stuh' ); ?>
							</label>
							<p class="description">
								<?php esc_html_e( 'When enabled, any site can access the update endpoints without authentication. Unverified requests are still logged. Use with caution.', 'stuh' ); ?>
							</p>
						</td>
					</tr>
				</table>
				<?php submit_button( __( 'Save Settings', 'stuh' ) ); ?>
			</form>

			<hr>
			<h2><?php esc_html_e( 'IP Whitelist', 'stuh' ); ?></h2>
			<p><?php esc_html_e( 'IPs listed here always have access to the update endpoints, even without an API key.', 'stuh' ); ?></p>

			<?php $whitelist = self::get_whitelist(); ?>
			<?php if ( ! empty( $whitelist ) ) : ?>
			<table class="wp-list-table widefat fixed striped" style="max-width:700px;margin-bottom:16px;">
				<thead>
					<tr>
						<th style="width:30%;"><?php esc_html_e( 'Label', 'stuh' ); ?></th>
						<th style="width:30%;"><?php esc_html_e( 'IP Address', 'stuh' ); ?></th>
						<th style="width:20%;"><?php esc_html_e( 'Added', 'stuh' ); ?></th>
						<th style="width:20%;"><?php esc_html_e( 'Actions', 'stuh' ); ?></th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ( $whitelist as $wl ) : ?>
					<tr>
						<td><strong><?php echo esc_html( $wl['label'] ); ?></strong></td>
						<td><code><?php echo esc_html( $wl['ip'] ); ?></code></td>
						<td><?php echo esc_html( date_i18n( 'Y-m-d', $wl['created_at'] ) ); ?></td>
						<td>
							<form method="post" style="display:inline-block;"
								  onsubmit="return confirm('Remove this IP from the whitelist?');">
								<?php wp_nonce_field( 'stuh_admin' ); ?>
								<input type="hidden" name="stuh_action" value="delete_whitelist">
								<input type="hidden" name="wl_id" value="<?php echo esc_attr( $wl['id'] ); ?>">
								<button type="submit" class="button" style="color:#d63638;border-color:#d63638;">
									<?php esc_html_e( 'Remove', 'stuh' ); ?>
								</button>
							</form>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php else : ?>
			<p><em><?php esc_html_e( 'No IPs whitelisted yet.', 'stuh' ); ?></em></p>
			<?php endif; ?>

			<form method="post" style="max-width:700px;">
				<?php wp_nonce_field( 'stuh_admin' ); ?>
				<input type="hidden" name="stuh_action" value="add_whitelist">
				<table class="form-table" role="presentation">
					<tr>
						<th scope="row">
							<label for="wl_name"><?php esc_html_e( 'Label', 'stuh' ); ?></label>
						</th>
						<td>
							<input type="text" id="wl_name" name="wl_name"
								   class="regular-text" placeholder="<?php esc_attr_e( 'e.g. Office', 'stuh' ); ?>" required>
						</td>
					</tr>
					<tr>
						<th scope="row">
							<label for="wl_ip"><?php esc_html_e( 'IP Address', 'stuh' ); ?></label>
						</th>
						<td>
							<input type="text" id="wl_ip" name="wl_ip"
								   class="regular-text" placeholder="<?php esc_attr_e( '203.0.113.1', 'stuh' ); ?>" required>
							<p class="description"><?php esc_html_e( 'IPv4 or IPv6. Ranges are not supported.', 'stuh' ); ?></p>
						</td>
					</tr>
				</table>
				<?php submit_button( __( 'Add to Whitelist', 'stuh' ), 'secondary' ); ?>
			</form>

			<hr>
			<h2><?php esc_html_e( 'Plugin Updates', 'stuh' ); ?></h2>
			<p>
				<?php
				$plugin_data = get_plugin_data( __FILE__ );
				/* translators: %s: current version number */
				printf( esc_html__( 'Current version: %s', 'stuh' ), '<strong>' . esc_html( $plugin_data['Version'] ) . '</strong>' );
				?>
			</p>
			<form method="post">
				<?php wp_nonce_field( 'stuh_admin' ); ?>
				<input type="hidden" name="stuh_action" value="check_for_updates">
				<?php submit_button( __( 'Check for Updates Now', 'stuh' ), 'secondary' ); ?>
			</form>

		</div>
		<?php
	}
}

// ============================================================
// GitHub client (adapted from switch-theme-updater)
// ============================================================
class STUH_GitHubClient {

	private string $token;
	private string $api;

	public function __construct( string $token, string $api ) {
		$this->token = $token;
		$this->api   = rtrim( $api, '/' );
	}

	private function headers(): array {
		$h = [
			'Accept'     => 'application/vnd.github+json',
			'User-Agent' => 'stuh-host/1.0',
		];
		if ( $this->token ) {
			$h['Authorization'] = 'Bearer ' . $this->token;
		}
		return $h;
	}

	private function request( string $method, string $url, $body = null ) {
		$args = [
			'method'  => $method,
			'headers' => $this->headers(),
			'timeout' => 30,
		];
		if ( null !== $body ) {
			$args['body'] = wp_json_encode( $body );
		}
		$res = wp_remote_request( $url, $args );
		if ( is_wp_error( $res ) ) {
			return $res;
		}
		$code = wp_remote_retrieve_response_code( $res );
		$data = json_decode( wp_remote_retrieve_body( $res ), true );
		if ( $code >= 200 && $code < 300 ) {
			return $data;
		}
		return new WP_Error(
			'github_error',
			'GitHub API ' . $code . ': ' . ( $data['message'] ?? 'unknown' )
		);
	}

	public function get_latest_version( string $repo, ?string $branch, string $path = '/', string $mode = 'releases' ): ?array {
		if ( 'commits' === $mode && $branch ) {
			$commits = $this->request(
				'GET',
				$this->api . '/repos/' . $repo . '/commits?sha=' . rawurlencode( $branch ) . '&per_page=1'
			);
			if ( ! is_wp_error( $commits ) && isset( $commits[0] ) ) {
				$sha        = $commits[0]['sha'];
				$style_path = ltrim( rtrim( $path, '/' ) . '/style.css', '/' );
				$file       = $this->request(
					'GET',
					$this->api . '/repos/' . $repo . '/contents/' . $style_path . '?ref=' . rawurlencode( $branch )
				);
				if ( ! is_wp_error( $file ) && isset( $file['content'] ) ) {
					$content = base64_decode( $file['content'] );
					if ( preg_match( '/Version:\s*(.+?)$/m', $content, $m ) ) {
						return [ 'version' => trim( $m[1] ), 'ref' => $sha ];
					}
				}
				return null;
			}
		}

		$rel = $this->request( 'GET', $this->api . '/repos/' . $repo . '/releases/latest' );
		if ( ! is_wp_error( $rel ) && isset( $rel['tag_name'] ) ) {
			return [ 'version' => ltrim( $rel['tag_name'], 'v' ), 'ref' => $rel['tag_name'] ];
		}
		return null;
	}

	public function get_version_from_tag( string $repo, string $tag, string $path = '/' ): ?array {
		$rel = $this->request( 'GET', $this->api . '/repos/' . $repo . '/releases/tags/' . rawurlencode( $tag ) );
		if ( is_wp_error( $rel ) || ! isset( $rel['tag_name'] ) ) {
			return null;
		}
		return [ 'version' => ltrim( $rel['tag_name'], 'v' ), 'ref' => $rel['tag_name'] ];
	}

	public function get_releases( string $repo ): array {
		$data = $this->request( 'GET', $this->api . '/repos/' . $repo . '/releases?per_page=100' );
		if ( is_wp_error( $data ) || ! is_array( $data ) ) {
			return [];
		}
		$out = [];
		foreach ( $data as $r ) {
			if ( isset( $r['tag_name'] ) ) {
				$out[] = [
					'tag'          => $r['tag_name'],
					'version'      => ltrim( $r['tag_name'], 'v' ),
					'name'         => $r['name'] ?: $r['tag_name'],
					'published_at' => $r['published_at'] ?? $r['created_at'] ?? '',
				];
			}
		}
		return $out;
	}

	/**
	 * Download a GitHub zipball, repackage it with the correct folder name,
	 * and return the path to the final zip file.
	 */
	public function download_zipball( string $repo, string $ref, string $path = '/', string $pack = '' ): string {
		if ( ! $pack ) {
			$pack = basename( $repo );
		}

		$temp_dir = get_temp_dir() . 'stuh-' . uniqid() . '-' . time();
		if ( ! wp_mkdir_p( $temp_dir ) ) {
			return new WP_Error( 'temp_dir', 'Failed to create temp directory' );
		}
		@chmod( $temp_dir, 0755 ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

		$zipball_url = $this->api . '/repos/' . $repo . '/zipball/' . rawurlencode( $ref );
		$response    = wp_remote_get( $zipball_url, [
			'timeout'    => 300,
			'headers'    => $this->headers(),
			'stream'     => false,
			'decompress' => false,
		] );

		if ( is_wp_error( $response ) ) {
			$this->rrmdir( $temp_dir );
			return $response;
		}

		$code = wp_remote_retrieve_response_code( $response );
		if ( 200 !== $code ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'download_failed', 'GitHub returned HTTP ' . $code );
		}

		$zip_data = wp_remote_retrieve_body( $response );
		if ( empty( $zip_data ) ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'empty_zip', 'Empty response from GitHub' );
		}

		$temp_zip = $temp_dir . '/download.zip';
		if ( false === file_put_contents( $temp_zip, $zip_data, LOCK_EX ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'write_failed', 'Failed to write zip' );
		}
		@chmod( $temp_zip, 0644 ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

		$extract_dir = $temp_dir . '/extract';
		if ( ! wp_mkdir_p( $extract_dir ) ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'extract_dir', 'Failed to create extract directory' );
		}

		if ( ! class_exists( 'ZipArchive' ) ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'no_zip', 'ZipArchive class not available' );
		}

		$zip    = new ZipArchive();
		$opened = $zip->open( $temp_zip );
		if ( true !== $opened ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'zip_open', 'Failed to open zip (error ' . $opened . ')' );
		}

		$extracted = $zip->extractTo( $extract_dir );
		$zip->close();
		if ( ! $extracted ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'zip_extract', 'Failed to extract zip' );
		}
		@unlink( $temp_zip ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

		$folders = glob( $extract_dir . '/*', GLOB_ONLYDIR );
		if ( empty( $folders ) ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'no_folder', 'No folder found after extraction' );
		}

		$source = $folders[0];
		if ( $path && '/' !== $path ) {
			$sub = $source . '/' . ltrim( $path, '/' );
			if ( ! is_dir( $sub ) ) {
				$this->rrmdir( $temp_dir );
				return new WP_Error( 'path_not_found', 'Sub-path not found: ' . $path );
			}
			$source = $sub;
		}

		$final_zip = $temp_dir . '/' . $pack . '.zip';
		$new_zip   = new ZipArchive();
		if ( true !== $new_zip->open( $final_zip, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
			$this->rrmdir( $temp_dir );
			return new WP_Error( 'final_zip', 'Failed to create final zip' );
		}
		$this->add_dir_to_zip( $new_zip, $source, $pack );
		$new_zip->close();
		@chmod( $final_zip, 0644 ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

		$this->rrmdir( $extract_dir );
		return $final_zip;
	}

	private function add_dir_to_zip( ZipArchive $zip, string $source_dir, string $prefix ): void {
		$source_dir = rtrim( $source_dir, '/\\' );
		$iter       = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator( $source_dir, RecursiveDirectoryIterator::SKIP_DOTS ),
			RecursiveIteratorIterator::SELF_FIRST
		);
		foreach ( $iter as $file ) {
			$rel      = substr( $file->getRealPath(), strlen( realpath( $source_dir ) ) + 1 );
			$zip_path = $prefix . '/' . $rel;
			$file->isDir() ? $zip->addEmptyDir( $zip_path ) : $zip->addFile( $file->getRealPath(), $zip_path );
		}
	}

	private function rrmdir( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}
		$iter = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator( $dir, FilesystemIterator::SKIP_DOTS ),
			RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ( $iter as $f ) {
			$f->isDir() ? rmdir( $f->getRealPath() ) : unlink( $f->getRealPath() );
		}
		@rmdir( $dir ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
	}
}

// Bootstrap.
new STUH_Plugin();

// Clean up the mu-plugin on deactivation.
register_deactivation_hook( __FILE__, [ 'STUH_Plugin', 'remove_mu_plugin' ] );
// Settings link in plugins list.
add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), function ( $links ) {
	array_unshift(
		$links,
		'<a href="' . esc_url( admin_url( 'admin.php?page=stuh' ) ) . '">' . esc_html__( 'Clients', 'stuh' ) . '</a>',
		'<a href="' . esc_url( admin_url( 'admin.php?page=stuh-settings' ) ) . '">' . esc_html__( 'Settings', 'stuh' ) . '</a>'
	);
	return $links;
} );
